### ISSUE TITLE
Exposure Events with automatic tracking and third-party analytics

### ISSUE THREAD

**Issue by adrianostas** [amplitude/experiment-js-client#113]
Hey! 

We have implemented the experiment-js-client in a Nuxt 3 app. We are using `automaticExposureTracking` with `exposureTrackingProvider` but it seems that the event is fired only when calling `variant()` for the first time. All subsequent `variant()` calls do not fire an `exposure` event. I'm not sure if this is expected since the [docs](https://amplitude.com/docs/sdks/experiment-sdks/experiment-javascript#variant) mention that every `variant()` call should fire an `exposure` event.

**Comment by bgiori** [comment]
Hey @adrianostas,

This is expected. The SDK uses an in memory cache of the last exposure sent for each flag/experiment to filter duplicate exposures for that same flag/experiment & variant.
