### ISSUE TITLE
Infinite polling without interval if `flagConfigPollingIntervalMillis` is not explicitly set

### ISSUE THREAD

**Issue by pdhoopr** [amplitude/experiment-js-client#144]
Hi there,

It looks like #141 introduced a configurable option for the flag polling interval with the intention that it would fall back to the default of 5 minutes if the option was not explicitly set. However after upgrading, I'm seeing that if I don't explicitly configure the new `flagConfigPollingIntervalMillis` option, then our app sends an infinite, rapid amount of polling requests without any timeout in between.

Looking through the PR, the interval value is computed and saved to the `ExperimentClient` config [here](https://github.com/amplitude/experiment-js-client/pull/141/files#diff-89e2f9492dbc9883abf3dd97aa80d1b16bba8760c71886183fb8c03d40650701R117-R121), but the value passed to the poller [here](https://github.com/amplitude/experiment-js-client/pull/141/files#diff-89e2f9492dbc9883abf3dd97aa80d1b16bba8760c71886183fb8c03d40650701R125) is actually the un-computed value from the `config` object passed to the constructor. So presumably the following change would work, if I'm following correctly:

```diff
    this.poller = new Poller(
      () => this.doFlags(),
-      config.flagConfigPollingIntervalMillis,
+      this.config.flagConfigPollingIntervalMillis,
    );
```

Thanks in advance for your help!

**Comment by bgiori** [comment]
Thanks! Fixed in `@amplitude/experiment-js-client@1.13.2` 🙏
