### ISSUE TITLE
apiKey and local-evaluation

### ISSUE THREAD

**Issue by sod** [amplitude/experiment-js-client#27]
We roll with https://developers.experiment.amplitude.com/docs/local-evaluation-alpha, thus we initialize `Experiment.initializeWithAmplitudeAnalytics` with `{ initialVariants: ... assignments from local evaluation ... }`.

As far as I understand in this mode we never want the Experiments sdk to fetch the assignments by itself, thus the apiKey is irrelevent. From looking at the code, it is only used for `fetch` and internal cache namespacing. But if we pass `undefined` as `apiKey`, the methods `all` and `variant` exit early and don't work and a few internals expect apiKey to be a string. So right now we just pass some random fixed value as apiKey.

That the sdk is not aware that you may run it like this is a bit confusing. But understandable, as local-evaluation is stil in alpha.

Do you plan to officially support "never fetch + initialVariants + no api" mode? E.g. if we pass `undefined` as `apiKey`, that this would automatically set the option `{ automaticFetchOnAmplitudeIdentityChange: false }` and the methods `all()` & `variant(...)` may stil work? Being able to tree shake away unused fetch code in this mode would be the cherry on top.

**Comment by bgiori** [comment]
Hi @sod thanks for submitting this issue. You should be able to pass in a hardcoded string for the api key to get past the checks until I can get a fix out to better support this use case.

Finally I would recommend setting `source: Source.InitialVariants` to always prefer the initial variants passed in as a result of local evaluation over any stale previously fetched variants.

Let me know if you have any questions, I'll keep this question open until we support this better.
