### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by sod** [amplitude/experiment-js-client#34]
Seeing the back and forth in this repository about IE11 hotfixes as of usage `'foo'.includes()`, i'd suggest removing `"es6"` from `"lib"` in https://github.com/amplitude/experiment-js-client/blob/main/tsconfig.json#L3 if you really have to support IE11. Then using `includes` on a string would have been a typescript error.

**Comment by sod** [comment]
Also https://github.com/amplitude/experiment-js-client/blob/fa6be45182569b3fe1f6a00204e031b6ae9747e1/packages/analyticsConnector/src/util/global.ts#L2 `global` doesn't exist by default in IE11 and throws an error

**Comment by bgiori** [comment]
Thanks @sod, that's a great idea.

**Comment by sod** [comment]
we don't care about IE11 anymore, so closing this.
